# Generated by Django 4.0.6 on 2023-04-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_too_user_account_too_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='too_username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
